# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path
# Add Yarn node_modules folder to the asset load path.
Rails.application.config.assets.paths << Rails.root.join('node_modules')


# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.
# Rails.application.config.assets.precompile += %w( admin.js admin.css )


Rails.application.config.assets.paths << Rails.root.join('vendor', 'assets')
Rails.application.config.assets.paths << Rails.root.join('app', 'assets', 'images')

# CSS
Rails.application.config.assets.precompile += %w( dist/css/bootstrap.min.css )
Rails.application.config.assets.precompile += %w( css/font-awesome.min )
Rails.application.config.assets.precompile += %w( nprogress.css )
Rails.application.config.assets.precompile += %w( iCheck/skins/flat/green.css )
Rails.application.config.assets.precompile += %w( css/bootstrap-progressbar-3.3.4.min )
Rails.application.config.assets.precompile += %w( dist/jqvmap.min )
Rails.application.config.assets.precompile += %w( daterangepicker )
Rails.application.config.assets.precompile += %w( application-theme/css/custom.min )
Rails.application.config.assets.precompile += %w( bin/prettify.min.css )
Rails.application.config.assets.precompile += %w( dist/css/select2.min.css )
Rails.application.config.assets.precompile += %w( dist/switchery.min.css )
Rails.application.config.assets.precompile += %w( dist/starrr.css )
Rails.application.config.assets.precompile += %w( build/css/bootstrap-datetimepicker.css )
Rails.application.config.assets.precompile += %w( normalize.css )
Rails.application.config.assets.precompile += %w( css/ion.rangeSlider.css )
Rails.application.config.assets.precompile += %w( css/ion.rangeSlider.skinFlat.css )
Rails.application.config.assets.precompile += %w( dist/css/bootstrap-colorpicker.min.css )
Rails.application.config.assets.precompile += %w( dist/cropper.min.css )
Rails.application.config.assets.precompile += %w( dist/min/dropzone.min.css )
Rails.application.config.assets.precompile += %w( dist/pnotify.css )
Rails.application.config.assets.precompile += %w( dist/pnotify.buttons.css )
Rails.application.config.assets.precompile += %w( dist/pnotify.nonblock.css )
Rails.application.config.assets.precompile += %w( dist/fullcalendar.min.css )
Rails.application.config.assets.precompile += %w( dist/fullcalendar.print.css )
Rails.application.config.assets.precompile += %w( css/dataTables.bootstrap.min.css )
Rails.application.config.assets.precompile += %w( css/buttons.bootstrap.min.css )
Rails.application.config.assets.precompile += %w( css/fixedHeader.bootstrap.min.css )
Rails.application.config.assets.precompile += %w( css/responsive.bootstrap.min.css )
Rails.application.config.assets.precompile += %w( css/scroller.bootstrap.min.css )
Rails.application.config.assets.precompile += %w( animate.min.css )

# JS
Rails.application.config.assets.precompile += %w( dist/jquery.min.js )
Rails.application.config.assets.precompile += %w( dist/js/bootstrap.bundle.min.js )
Rails.application.config.assets.precompile += %w( lib/fastclick.js )
Rails.application.config.assets.precompile += %w( nprogress.js )
Rails.application.config.assets.precompile += %w( dist/Chart.min.js )
Rails.application.config.assets.precompile += %w( dist/jquery.sparkline.min.js )
Rails.application.config.assets.precompile += %w( raphael.min.js )
Rails.application.config.assets.precompile += %w( morris.min.js )
Rails.application.config.assets.precompile += %w( dist/gauge.min.js )
Rails.application.config.assets.precompile += %w( bootstrap-progressbar.min.js )
Rails.application.config.assets.precompile += %w( icheck.min.js )
Rails.application.config.assets.precompile += %w( skycons.js )
Rails.application.config.assets.precompile += %w( jquery.flot.js )
Rails.application.config.assets.precompile += %w( jquery.flot.pie.js )
Rails.application.config.assets.precompile += %w( jquery.flot.time.js )
Rails.application.config.assets.precompile += %w( jquery.flot.stack.js )
Rails.application.config.assets.precompile += %w( jquery.flot.resize.js )
Rails.application.config.assets.precompile += %w( js/jquery.flot.orderBars.js )
Rails.application.config.assets.precompile += %w( js/jquery.flot.spline.min.js )
Rails.application.config.assets.precompile += %w( curvedLines.js )
Rails.application.config.assets.precompile += %w( build/date.js )
Rails.application.config.assets.precompile += %w( dist/jquery.vmap.js )
Rails.application.config.assets.precompile += %w( dist/maps/jquery.vmap.world.js )
Rails.application.config.assets.precompile += %w( dist/maps/jquery.vmap.usa.js )
Rails.application.config.assets.precompile += %w( examples/js/jquery.vmap.sampledata.js )
Rails.application.config.assets.precompile += %w( min/moment.min.js )
Rails.application.config.assets.precompile += %w( daterangepicker.js )
Rails.application.config.assets.precompile += %w( js/custom.min.js )

Rails.application.config.assets.precompile += %w( js/bootstrap-wysiwyg.min.js )
Rails.application.config.assets.precompile += %w( jquery.hotkeys.js )
Rails.application.config.assets.precompile += %w( src/prettify.js )
Rails.application.config.assets.precompile += %w( src/jquery.tagsinput.js )
Rails.application.config.assets.precompile += %w( dist/switchery.min.js )
Rails.application.config.assets.precompile += %w( dist/js/select2.full.min.js )
Rails.application.config.assets.precompile += %w( dist/parsley.min.js )
Rails.application.config.assets.precompile += %w( dist/autosize.min.js )
Rails.application.config.assets.precompile += %w( dist/jquery.autocomplete.min.js )
Rails.application.config.assets.precompile += %w( dist/starrr.js )
Rails.application.config.assets.precompile += %w( build/js/bootstrap-datetimepicker.min.js )
Rails.application.config.assets.precompile += %w( js/ion.rangeSlider.min.js )
Rails.application.config.assets.precompile += %w( dist/js/bootstrap-colorpicker.min.js )
Rails.application.config.assets.precompile += %w( dist/min/jquery.inputmask.bundle.min.js )
Rails.application.config.assets.precompile += %w( dist/jquery.knob.min.js )
Rails.application.config.assets.precompile += %w( dist/cropper.min.js )
Rails.application.config.assets.precompile += %w( multifield.js )
Rails.application.config.assets.precompile += %w( validator.js )
Rails.application.config.assets.precompile += %w( js/jquery.smartWizard.js )
Rails.application.config.assets.precompile += %w( dist/min/dropzone.min.js )
Rails.application.config.assets.precompile += %w( dist/pnotify.js )
Rails.application.config.assets.precompile += %w( dist/pnotify.buttons.js )
Rails.application.config.assets.precompile += %w( dist/pnotify.nonblock.js )
Rails.application.config.assets.precompile += %w( dist/jquery.sparkline.min.js )
Rails.application.config.assets.precompile += %w( dist/jquery.easypiechart.min.js )
Rails.application.config.assets.precompile += %w( bootstrap-progressbar.min.js )
Rails.application.config.assets.precompile += %w( dist/fullcalendar.min.js )
Rails.application.config.assets.precompile += %w( js/jquery.dataTables.min.js )
Rails.application.config.assets.precompile += %w( js/dataTables.bootstrap.min.js )
Rails.application.config.assets.precompile += %w( js/dataTables.buttons.min.js )
Rails.application.config.assets.precompile += %w( js/buttons.bootstrap.min.js )
Rails.application.config.assets.precompile += %w( js/buttons.flash.min.js )
Rails.application.config.assets.precompile += %w( js/buttons.html5.min.js )
Rails.application.config.assets.precompile += %w( js/buttons.print.min.js )
Rails.application.config.assets.precompile += %w( js/dataTables.fixedHeader.min.js )
Rails.application.config.assets.precompile += %w( js/dataTables.keyTable.min.js )
Rails.application.config.assets.precompile += %w( js/dataTables.responsive.min.js )
Rails.application.config.assets.precompile += %w( js/responsive.bootstrap.js )
Rails.application.config.assets.precompile += %w( js/dataTables.scroller.min.js )
Rails.application.config.assets.precompile += %w( dist/jszip.min.js )
Rails.application.config.assets.precompile += %w( build/pdfmake.min.js )
Rails.application.config.assets.precompile += %w( build/vfs_fonts.js )
Rails.application.config.assets.precompile += %w( dist/echarts.min.js )
Rails.application.config.assets.precompile += %w( map/js/world.js )

# Fuentes
Rails.application.config.assets.paths << Rails.root.join("app", "assets", "fonts")